# Generated by Django 5.0.2 on 2025-11-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    def generate_menu(apps, schema_editor):
        Menu = apps.get_model("menus", "Menu")
        MenuItem = apps.get_model("menus", "MenuItem")

        if Menu.objects.filter(slug="main_menu").exists():
            return

        menu = Menu.objects.create(title="Main menu", slug="main_menu")

        home = MenuItem.objects.create(
            menu=menu,
            title="Главная",
            named_url="home",
            order=1,
        )
        docs = MenuItem.objects.create(
            menu=menu,
            title="Документация",
            url="/docs/",
            order=2,
        )
        MenuItem.objects.create(
            menu=menu,
            parent=docs,
            title="API",
            url="/docs/api/",
            order=1,
        )
        MenuItem.objects.create(
            menu=menu,
            parent=docs,
            title="FAQ",
            url="/docs/faq/",
            order=2,
        )
        MenuItem.objects.create(
            menu=menu,
            parent=docs,
            title="Релизы",
            url="/docs/releases/",
            order=3,
        )
        MenuItem.objects.create(
            menu=menu,
            parent=docs,
            title="API v1",
            url="/docs/api/v1/",
            order=4,
        )

        MenuItem.objects.create(
            menu=menu,
            title="Тарифы",
            url="/pricing/",
            order=3,
        )
        MenuItem.objects.create(
            menu=menu,
            title="Контакты",
            named_url="contacts",
            order=4,
        )

    def delete_menu(apps, schema_editor):
        Menu = apps.get_model("menus", "Menu")
        Menu.objects.filter(slug="main_menu").delete()

    operations = [
        migrations.RunPython(generate_menu, delete_menu),
    ]
